---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: 包含多項新功能與增強功能。Cloud Volumes ONTAP 
---
= 更新功能Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
包含多項新功能與增強功能。Cloud Volumes ONTAP

最新版Cloud Manager也會提供其他功能與增強功能。請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Manager版本資訊"^] 以取得詳細資料。



== 9.7 P6（2020年8月15日）

9.7版的Cloud Volumes ONTAP 更新版本適用於整個過程、現在可透過Cloud Manager 3.8或更新版本取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P6["檢視在p6修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 多個BYOL授權以增加容量（2020年8月3日）

您現在可以購買Cloud Volumes ONTAP 多個適用於某個不支援的BYOL系統授權、以配置超過3668 TiB的容量。例如、您可能會購買兩份授權、以配置多達736 TiB的容量來Cloud Volumes ONTAP 供使用。您也可以購買四份授權、最多可取得1.4 PIB。

單一節點系統或 HA 配對可購買的授權數量不受限制。

請注意、磁碟限制可能會讓您無法單獨使用磁碟來達到容量限制。您可以超越磁碟限制 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["將非作用中資料分層至物件儲存設備"^]。如需磁碟限制的相關資訊、請參閱本版本說明中的儲存限制。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html["瞭解如何將額外的系統授權新增Cloud Volumes ONTAP 至功能完善"^]。



== AWS中的9.7 P5（2020年7月27日）

AWS現在提供了更新版本的更新版本。Cloud Volumes ONTAP此修補程式版本包含錯誤修正、並支援新的EC2執行個體類型。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P5["檢視在P5修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



=== 支援新的EC2執行個體類型

支援下列EC2執行個體類型的Premium和BYOL授權：Cloud Volumes ONTAP

* c5n.9xlarge
* c5n.18xlarge




== Azure中的9.7 P5（2020年7月20日）

Microsoft Azure現已推出更新版本：Cloud Volumes ONTAP此修補程式版本包含錯誤修正、並支援新的VM類型。

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P5["檢視在P5修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



=== 支援使用Ultra SSD VNVRAM的新VM類型

支援下列VM類型的單一節點系統具備Premium或BYOL授權：Cloud Volumes ONTAP

* Standard_E32s_v3
* Standard_E48s_v3


E32s_v3 VM類型使用 https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd["超SSD"^] 適用於VNVRAM、可提供更佳的寫入效能。

目前支援這些VM類型的地區如下：US Gov Virginia、South Central US和West US。



== 支援AWS中的多個儲存VM（2020年7月16日）

現在、支援AWS中的多個儲存VM（SVM）Cloud Volumes ONTAP 。

當您攜帶自己的授權（BYOL）時、可以使用c5、M5和R5執行個體類型來支援多個儲存VM。支援的儲存VM數量如下：

* 12個儲存VM搭配單一節點系統
* 8個儲存VM、搭配HA配對


在預設設定Cloud Volumes ONTAP 為使用「支援」的第一個儲存VM之外、每個額外的_data-Serving儲存VM都需要附加授權。請聯絡您的客戶團隊以取得 SVM 附加授權。

您設定用於災難恢復（DR）的儲存VM不需要附加授權（免費）、但它們確實會根據儲存VM的限制而計算。

例如、如果HA配對上有8個資料服務儲存VM、則您已達到上限、無法建立任何其他儲存VM。另一個HA配對也一樣、它有8個儲存VM設定用於災難恢復、您已經達到極限、無法建立任何額外的儲存VM。

必須透過System Manager或CLI建立其他儲存VM。



== Azure中的德國疏芬地區不再受到支援（2020年6月26日）

下列Azure地區不再支援此功能：Cloud Volumes ONTAP

* 德國中部（Sovereign）
* 德國東北（Sovereign）


NetApp持續支援Cloud Volumes ONTAP 德國地區的部門：

* 德國北部（公共）
* 德國West Central（公共）


https://cloud.netapp.com/cloud-volumes-global-regions["請參閱支援的Azure地區完整清單"^]。



== 9.7 P4（2020年6月2日）

9.7 P4 for Cloud Volumes ONTAP NetApp的修補程式版本現在可透過Cloud Manager 3.8及更新版本取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P4["檢視P4修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.7 P3（2020年5月2日）

9.7版P3 for Cloud Volumes ONTAP NetApp的修補程式現已可透過Cloud Manager 3.8及更新版本取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P3["檢視P3修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.7 P2（2020年4月8日）

9.7 P2的Cloud Volumes ONTAP 更新版本適用於整個過程、現在可透過Cloud Manager 3.8及更新版本取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P2["檢視P2修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 提高Google Cloud的磁碟容量（2020年3月13日）

在Google Cloud中使用Premium或BYOL授權時、您現在可以將多達256個TiB的持續磁碟附加Cloud Volumes ONTAP 至執行功能。此容量從64 TB增加至64 TB。

就像以前一樣、您可以將持續性磁碟與資料分層至物件儲存設備、結合使用Premium和BYOL的最高系統容量達368 TiB。

每個系統的資料磁碟數量上限也增加至124個磁碟。

* link:reference-configs-gcp.html["深入瞭解Google Cloud Volumes ONTAP Cloud支援的支援功能組態"]
* link:reference-limits-gcp.html["檢閱Google Cloud的儲存限制"]




== 9.7 P1（2020年3月6日）

9.7 P1版的Cloud Volumes ONTAP 更新版本適用於整個過程、現在可透過Cloud Manager 3.8及更新版本取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P1["檢視P1修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== AWS更新（2020年2月16日）

我們已推出新EC2執行個體的支援、以及支援的資料磁碟數量的變更。



=== 支援新執行個體

使用Premium或BYOL授權時、目前支援多種Cloud Volumes ONTAP 新型EC2執行個體類型的功能：

* c5.9xlarge
* c5d.18xlarge ^1^
* m5d.8xlarge ^1^
* m5d.12xlarge ^1^
* m5.16xlarge
* r5.8xlarge
* r5.12xlarge ^2^


^1^這些執行個體類型包括本機NVMe儲存設備、Cloud Volumes ONTAP 此儲存設備用作_Flash Cache。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["深入瞭解"^]。

^2^ r5.12xlarge執行個體類型具有已知的支援限制。如果節點因發生緊急狀況而意外重新開機、系統可能不會收集用於疑難排解的核心檔案、而會造成問題的根本原因。客戶接受風險及有限支援條款、並在發生此情況時承擔所有支援責任。

https://aws.amazon.com/ec2/instance-types/["深入瞭解這些EC2執行個體類型"^]。

link:reference-configs-aws.html["深入瞭解AWS支援的9.7組態"]。



=== 支援的資料磁碟

現在、對於c5、m5和R5執行個體、可減少一個資料磁碟。對於單一節點系統、支援22個資料磁碟。對於HA配對、每個節點支援19個資料磁碟。

link:reference-limits-aws.html["深入瞭解AWS的儲存限制"]。



== 支援Azure中的DS15_v2（2020年2月12日）

目前、無論是單一節點系統或HA配對、Azure中的DS15_v2虛擬機器類型都支援此功能。Cloud Volumes ONTAP

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["深入瞭解DSv2系列"^]。

link:reference-configs-azure.html["深入瞭解Azure支援的9.7組態"]。



== 9.7 GA（2020年2月10日）

AWS和Google Cloud現已推出《通用版本》（GA）版本Cloud Volumes ONTAP 的《資訊》（General Availability、GA）。GA版本包含錯誤修正。Cloud Manager會提示您將現有系統升級至此版本。



== Azure 9.7 D1（2020年1月29日）

Microsoft Azure現已推出更新版本：Cloud Volumes ONTAP

我們發現Cloud Volumes ONTAP 有一個問題、就是在Cloud Volumes ONTAP Azure虛擬機器重新啟動的情況下、無法成功啟動不完整的功能。

此問題已在9.7 D1（及更新版本）中修正。我們強烈建議Cloud Volumes ONTAP 您盡快升級至最新版的更新版本。

如果您有任何問題、請使用產品內對談或聯絡我們 https://www.netapp.com/us/contact-us/support.aspx[]。



== 9.7 RC1（2019年12月16日）

目前AWS、Azure和Google Cloud Platform均提供此產品的適用版本。Cloud Volumes ONTAP除了所介紹的功能之外 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["更新ONTAP"^]、Cloud Volumes ONTAP 本版的《》包含下列內容：

* <<Azure中的Flash Cache支援>>
* <<修正Azure NIC分離事件>>




=== Azure中的Flash Cache支援

目前支援Standard _L8s_v2 VM類型、搭配Azure中的單一節點BYOL系統。Cloud Volumes ONTAP這種VM類型包括本機NVMe儲存設備、Cloud Volumes ONTAP 這些儲存設備以_Flash Cache的形式使用。

Flash Cache 可透過即時智慧快取來加速資料存取、快取最近讀取的使用者資料和 NetApp 中繼資料。它適用於隨機讀取密集的工作負載、包括資料庫、電子郵件和檔案服務。

使用此VM類型部署新系統、或修改現有系統以使用此VM類型、您就能自動善用Flash Cache。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["深入瞭解啟用Cloud Volumes ONTAP Flash Cache on支援的相關資訊、包括資料壓縮的限制"^]。



=== 修正Azure NIC分離事件

此版本可解決Cloud Volumes ONTAP 從Azure NIC分離事件重新啟動節點時發生的問題。而不中斷服務、也能更妥善地處理這些事件。Cloud Volumes ONTAP雖然從Azure凍結維護事件中、雖然仍會執行接管/回饋順序、但在此期間可能不會再從NIC分離重新開機。Cloud Volumes ONTAP



== 升級附註

* 必須從 Cloud Manager 完成升級。 Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。
* 您可以從Cloud Volumes ONTAP 9.6版升級至32版。Cloud Manager會提示您將現有Cloud Volumes ONTAP 的NetApp 9.6系統升級至9.7版。
+
http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在Cloud Manager通知您的情況下進行升級"^]。

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。

